package pro.pro;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;


public class MainController implements Initializable{
	@FXML
	private AnchorPane MainPanel;

	// Event Listener on Button.onAction
	@FXML
	public void Attend(ActionEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("attendance.fxml"));
		MainPanel.getChildren().setAll(pane);
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void Add(ActionEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("addMember.fxml"));
		MainPanel.getChildren().setAll(pane);
	}
	// Event Listener on Button.onAction
	@FXML
	public void Find(ActionEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("findMember.fxml"));
		MainPanel.getChildren().setAll(pane);
	}
	// Event Listener on Button.onAction
	@FXML
	public void Payment(ActionEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("memberPayment.fxml"));
		MainPanel.getChildren().setAll(pane);
	}
	// Event Listener on Button.onAction
	@FXML
	public void Mail(ActionEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("Emails.fxml"));
		MainPanel.getChildren().setAll(pane);
	}
	// Event Listener on Button.onAction
	@FXML
	public void Notification(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void Report(ActionEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("report.fxml"));
		MainPanel.getChildren().setAll(pane);
	}
	// Event Listener on Button.onAction
	@FXML
	public void Settings(ActionEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("settings.fxml"));
		MainPanel.getChildren().setAll(pane);
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		AnchorPane pane = null;
		try {
			pane = FXMLLoader.load(getClass().getResource("attendance.fxml"));
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		MainPanel.getChildren().setAll(pane);
	}
	}

